import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { FiArrowUpRight, FiDownload, FiGithub, FiLinkedin, FiMail, FiMenu, FiMoon, FiSun, FiX } from 'react-icons/fi';
import './styles.css';

const navItems = ['About', 'Skills', 'Projects', 'Education', 'Contact'];
const skills = [['Programming', [['C', 'Comfortable'], ['C++', 'Comfortable'], ['Java', 'Learning'], ['Python', 'Intermediate'], ['JavaScript', 'Intermediate'], ['SQL', 'Comfortable']]], ['Framework', [['React', 'Intermediate']]], ['UI / UX', [['Figma', 'Comfortable'], ['Photoshop', 'Learning']]], ['Tools', [['Git', 'Comfortable'], ['GitHub', 'Comfortable'], ['VS Code', 'Intermediate']]]];

// EDIT HERE: add each project's repository and deployed demo URL.
const projects = [
  { name: 'Bible Presentation App', type: 'Desktop application', tech: 'React | Electron | Firebase', copy: 'A focused desktop tool for finding and presenting Bible verses.', tone: 'violet', image: '/images/Bible-Presenter.png', github: 'https://github.com/SamJ1005/Bible-Presenter/', demo: 'scripture-screen-browser.vercel.app' },
  { name: 'Solar Project', type: 'Academic project', tech: 'JavaScript | HTML | CSS | Three.js', copy: 'An academic project exploring solar energy concepts.', tone: 'amber', image: '/images/Planetarium.png', github: 'https://github.com/SamJ1005/Planetarium/', demo: 'solar-planetarium.netlify.app' },
];
function externalUrl(url) { return /^https?:\/\//i.test(url) ? url : `https://${url}`; }

function ThemeToggle({ isDark, onToggle }) { return <button className="icon-button" onClick={onToggle} aria-label="Toggle colour theme">{isDark ? <FiSun /> : <FiMoon />}</button>; }
function Header({ isDark, onToggle }) { const [open, setOpen] = useState(false); const [active, setActive] = useState('home'); useEffect(() => { const sections = ['home', ...navItems.map((item) => item.toLowerCase())].map((id) => document.getElementById(id)).filter(Boolean); const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActive(visible.target.id); }, { rootMargin: '-25% 0px -60% 0px', threshold: [0.05, 0.25, 0.6] }); sections.forEach((section) => observer.observe(section)); return () => observer.disconnect(); }, []); const link = (item) => <a className={active === item.toLowerCase() ? 'active' : ''} aria-current={active === item.toLowerCase() ? 'page' : undefined} key={item} href={`#${item.toLowerCase()}`} onClick={() => setOpen(false)}>{item}</a>; return <header className="site-header"><a className={`brand ${active === 'home' ? 'active' : ''}`} href="#home">S<span>.</span></a><nav className="desktop-nav" aria-label="Main navigation">{navItems.map(link)}</nav><div className="header-actions"><ThemeToggle isDark={isDark} onToggle={onToggle} /><button className="icon-button menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <FiX /> : <FiMenu />}</button></div>{open && <nav className="mobile-nav" aria-label="Mobile navigation">{navItems.map(link)}</nav>}</header>; }
function Button({ href, children, secondary = false, icon }) { return <a className={`button ${secondary ? 'button-secondary' : ''}`} href={href}>{children}{icon}</a>; }
function SectionHeading({ label, title, description }) { return <div className="section-heading"><p className="eyebrow">{label}</p><h2>{title}</h2>{description && <p className="section-description">{description}</p>}</div>; }
function Home() { return <section className="hero" id="home"><div className="hero-copy"><motion.p className="eyebrow" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>Computer Science Student</motion.p><motion.h1 initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>Hi, I&apos;m Sam.<br /><span>I build while I learn.</span></motion.h1><motion.p className="hero-lede" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>An aspiring computer science student learning through thoughtful projects, from desktop tools to web experiences.</motion.p><motion.div className="button-row" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><Button href="#projects" icon={<FiArrowUpRight />}>View projects</Button><Button href="https://github.com/SamJ1005/" secondary icon={<FiGithub />}>GitHub</Button><Button href="/images/MYRESUME.pdf" secondary icon={<FiDownload />}>Download resume</Button></motion.div></div><div className="hero-visual" aria-hidden="true"><div className="visual-card"><FiGithub /><span>learn<br />by building.</span></div><i className="visual-dot dot-one" /><i className="visual-dot dot-two" /></div></section>; }
function About() { return <section className="content-section" id="about"><SectionHeading label="01 - About" title="Learning by making useful things." /><div className="about-grid"><p className="about-lead">I&apos;m a Computer Science student who enjoys understanding how software works by building it.</p><div className="about-copy"><p>My interests include desktop applications, web development, designing, app develepment and technical services. I like the point where a technical idea becomes a clear, usable interface.</p><p>I&apos;m continuously improving my skills through hands-on projects and genarating newer ideas.</p></div></div></section>; }
function Skills() { return <section className="content-section" id="skills"><SectionHeading label="02 - Skills" title="Technical arsenal." description="An honest view of the technologies I am currently learning and using." /><div className="skill-grid">{skills.map(([group, items]) => <motion.article className="skill-card arsenal-card" key={group} whileHover={{ y: -4 }} transition={{ duration: .2 }}><h3>{group}</h3><div className="skill-pills">{items.map(([name]) => <span className="skill-pill" key={name}>{name}</span>)}</div></motion.article>)}</div></section>; }
function Projects() { return <section className="content-section" id="projects"><SectionHeading label="03 - Projects" title="My Projects" description="Projects where I have explored software, interfaces, and problem-solving." /><div className="projects-grid">{projects.map((project) => <motion.article className="project-card" key={project.name} whileHover={{ y: -5 }}><div className={`project-art ${project.tone}`}><div className="art-window"><div className="art-dots"><i /><i /><i /></div><div className="art-placeholder">{project.tone === 'violet' ? 'Presentation mode' : 'Solar energy'}</div><img className="project-screenshot" src={project.image} alt={`${project.name} screenshot`} onError={(event) => { event.currentTarget.style.display = 'none'; }} /></div></div><div className="card-content"><p className="card-tag">{project.type}</p><h3>{project.name}</h3><p>{project.copy}</p><p className="project-tech">{project.tech}</p><div className="card-links"><a href={externalUrl(project.github)} target="_blank" rel="noreferrer">GitHub <FiArrowUpRight /></a><a href={externalUrl(project.demo)} target="_blank" rel="noreferrer">Live demo <FiArrowUpRight /></a></div></div></motion.article>)}</div></section>; }
function Education() { return <section className="content-section" id="education"><SectionHeading label="04 - Education" title="The foundation." description="My educational details." /><div className="timeline"><article><span>Present</span><div><h3>Bachelor of Computer Application (BCA)</h3><strong>St Joseph&apos;s University, Bengaluru</strong><p>Currently studying 5th Semester, 3rd Year.</p></div></article><article><span>PUC</span><div><h3>CEBA</h3><strong>St Joseph&apos;s Indian Composite PU College</strong><p>Marks / Percentage: 92.83%</p></div></article><article><span>SSLC</span><div><h3>Schooling</h3><strong>Eshwari Education Society</strong><p>Marks / Percentage: 84%</p></div></article></div></section>; }
function Contact() { function handleSubmit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const subject = encodeURIComponent(`Portfolio message from ${form.get('name') || 'a visitor'}`); const body = encodeURIComponent(`${form.get('message') || ''}\n\nReply to: ${form.get('email') || ''}`); window.location.href = `mailto:samjac7755@gmail.com?subject=${subject}&body=${body}`; } return <section className="content-section" id="contact"><SectionHeading label="05 - Contact" title="Let&apos;s start a conversation." description="I am open to internship opportunities, project discussions, and feedback." /><div className="contact-grid"><div className="contact-links"><a href="mailto:samjac7755@gmail.com"><FiMail /> samjac7755@gmail.com <FiArrowUpRight /></a><a href="https://github.com/SamJ1005/" target="_blank" rel="noreferrer"><FiGithub /> GitHub <FiArrowUpRight /></a><a href="https://www.linkedin.com/in/sam-jack-2a39b6343" target="_blank" rel="noreferrer"><FiLinkedin /> LinkedIn <FiArrowUpRight /></a></div><form onSubmit={handleSubmit}><label>Name<input name="name" placeholder="Your name" /></label><label>Email<input name="email" type="email" placeholder="you@example.com" /></label><label>Message<textarea name="message" rows="4" placeholder="What would you like to talk about?" /></label><button className="button" type="submit">Open email <FiArrowUpRight /></button></form></div></section>; }
function App() { const [isDark, setDark] = useState(true); useEffect(() => { document.documentElement.dataset.theme = isDark ? 'dark' : 'light'; }, [isDark]); useEffect(() => { const form = document.querySelector('#contact form'); if (!form) return undefined; const openGmail = (event) => { event.preventDefault(); event.stopImmediatePropagation(); const data = new FormData(form); const subject = encodeURIComponent(`Portfolio message from ${data.get('name') || 'a visitor'}`); const body = encodeURIComponent(`${data.get('message') || ''}\n\nReply to: ${data.get('email') || ''}`); window.open(`https://mail.google.com/mail/?view=cm&fs=1&to=samjac7755@gmail.com&su=${subject}&body=${body}`, '_blank', 'noopener,noreferrer'); }; form.addEventListener('submit', openGmail, true); return () => form.removeEventListener('submit', openGmail, true); }, []); return <><Header isDark={isDark} onToggle={() => setDark(!isDark)} /><Home /><main><About /><Skills /><Projects /><Education /><Contact /></main><footer>© {new Date().getFullYear()} Sam</footer></>; }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
